apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicpulse

resources:
  - ../../base

images:
  - name: ghcr.io/hussainali-code/civicpulse-backend
    newTag: 1.0.0
  - name: ghcr.io/hussainali-code/civicpulse-frontend
    newTag: 1.0.0

patches:
  # Production configuration adjustments
  - target:
      kind: ConfigMap
      name: civicpulse-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "production"
      - op: replace
        path: /data/TRIAGE_PROVIDER
        value: "llm"
  # Production Ingress with production domain and TLS annotations
  - target:
      kind: Ingress
      name: civicpulse-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "civicpulse.example.com"
